import {
  Boxes,
  Building2,
  CreditCard,
  Layers3,
  Package,
  Ruler,
  Store,
  Tags,
  Truck,
  UserRound,
  Users,
  Warehouse,
} from '@lucide/vue'
import type { AdminResourceConfig } from '~/types/admin'

const activeOptions = [
  { label: 'Activo', value: true },
  { label: 'Inactivo', value: false },
]

const documentOptions = [
  { label: 'DUI', value: 'dui' },
  { label: 'NIT', value: 'nit' },
  { label: 'Pasaporte', value: 'passport' },
  { label: 'Otro', value: 'other' },
]

export const adminResourceConfigs: Record<string, AdminResourceConfig> = {
  products: {
    title: 'Productos',
    description: 'Catalogo comercial con precio, costo, impuesto y relaciones de inventario.',
    endpoint: '/products',
    collectionKey: 'products',
    resourceKey: 'product',
    permission: 'products.read',
    writePermission: 'products.write',
    icon: Package,
    singularLabel: 'producto',
    createLabel: 'Nuevo producto',
    emptyTitle: 'Sin productos',
    emptyDescription: 'Agrega el primer producto para venderlo desde POS y mover inventario.',
    searchPlaceholder: 'Buscar por nombre o SKU',
    searchParam: 'name',
    dependencies: [
      { key: 'categories', endpoint: '/categories', collectionKey: 'categories' },
      { key: 'units', endpoint: '/units', collectionKey: 'units' },
      { key: 'brands', endpoint: '/brands', collectionKey: 'brands' },
    ],
    fields: [
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Cafe molido 400g' },
      { key: 'sku', label: 'SKU', required: true, placeholder: 'CAF-001' },
      { key: 'barcode', label: 'Codigo de barras', placeholder: '750100000001' },
      { key: 'category_id', label: 'Categoria', type: 'select', dependencyKey: 'categories', required: true },
      { key: 'unit_id', label: 'Unidad', type: 'select', dependencyKey: 'units', required: true },
      { key: 'brand_id', label: 'Marca', type: 'select', dependencyKey: 'brands', required: true },
      { key: 'cost', label: 'Costo', type: 'number', defaultValue: '0.00', required: true },
      { key: 'price', label: 'Precio', type: 'number', defaultValue: '0.00', required: true },
      { key: 'tax_rate', label: 'IVA', type: 'number', defaultValue: '0.13', required: true },
      { key: 'description', label: 'Descripcion', type: 'textarea', class: 'md:col-span-2' },
      { key: 'track_inventory', label: 'Controlar inventario', type: 'boolean', defaultValue: true },
      { key: 'active', label: 'Activo', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'name', label: 'Producto' },
      { key: 'sku', label: 'SKU' },
      { key: 'category_name', label: 'Categoria' },
      { key: 'price', label: 'Precio', type: 'money' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
    formClass: 'md:grid-cols-2',
  },
  categories: {
    title: 'Categorias',
    description: 'Organiza el catalogo de productos por familias y subfamilias.',
    endpoint: '/categories',
    collectionKey: 'categories',
    resourceKey: 'category',
    permission: 'categories.read',
    writePermission: 'categories.write',
    icon: Layers3,
    singularLabel: 'categoria',
    createLabel: 'Nueva categoria',
    emptyTitle: 'Sin categorias',
    emptyDescription: 'Crea categorias para mantener el catalogo ordenado.',
    searchPlaceholder: 'Buscar categoria',
    searchParam: 'name',
    dependencies: [
      { key: 'categories', endpoint: '/categories', collectionKey: 'categories' },
    ],
    fields: [
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Bebidas' },
      { key: 'parent_id', label: 'Categoria padre', type: 'select', dependencyKey: 'categories' },
      { key: 'active', label: 'Activa', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'name', label: 'Categoria' },
      { key: 'parent_id', label: 'Padre' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
  },
  units: {
    title: 'Unidades de medida',
    description: 'Unidades usadas por productos, compras e inventario.',
    endpoint: '/units',
    collectionKey: 'units',
    resourceKey: 'unit',
    permission: 'units.read',
    writePermission: 'units.write',
    icon: Ruler,
    singularLabel: 'unidad',
    createLabel: 'Nueva unidad',
    emptyTitle: 'Sin unidades',
    emptyDescription: 'Agrega unidades como UND, CAJA, KG o L.',
    searchPlaceholder: 'Buscar unidad',
    fields: [
      { key: 'code', label: 'Codigo', required: true, placeholder: 'UND' },
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Unidad' },
      { key: 'active', label: 'Activa', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'code', label: 'Codigo' },
      { key: 'name', label: 'Unidad' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
  },
  brands: {
    title: 'Marcas',
    description: 'Marcas comerciales para clasificar productos.',
    endpoint: '/brands',
    collectionKey: 'brands',
    resourceKey: 'brand',
    permission: 'brands.read',
    writePermission: 'brands.write',
    icon: Tags,
    singularLabel: 'marca',
    createLabel: 'Nueva marca',
    emptyTitle: 'Sin marcas',
    emptyDescription: 'Crea marcas para enriquecer busquedas y reportes.',
    searchPlaceholder: 'Buscar marca',
    searchParam: 'name',
    fields: [
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Generica' },
      { key: 'active', label: 'Activa', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'name', label: 'Marca' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
  },
  customers: {
    title: 'Clientes',
    description: 'Datos comerciales y fiscales para ventas, tickets y documentos.',
    endpoint: '/customers',
    collectionKey: 'customers',
    resourceKey: 'customer',
    permission: 'customers.read',
    writePermission: 'customers.write',
    icon: Users,
    singularLabel: 'cliente',
    createLabel: 'Nuevo cliente',
    emptyTitle: 'Sin clientes',
    emptyDescription: 'Agrega clientes para asociarlos a ventas y facturacion.',
    searchPlaceholder: 'Buscar por nombre, NIT o telefono',
    searchParam: 'name',
    fields: [
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Cliente Final' },
      { key: 'document_type', label: 'Tipo de documento', type: 'select', options: documentOptions },
      { key: 'document_number', label: 'Documento', placeholder: '01234567-8' },
      { key: 'nit', label: 'NIT', placeholder: '0614-010190-101-0' },
      { key: 'nrc', label: 'NRC', placeholder: '123456-7' },
      { key: 'email', label: 'Correo', type: 'email', placeholder: 'cliente@example.com' },
      { key: 'phone', label: 'Telefono', placeholder: '7777-7777' },
      { key: 'address', label: 'Direccion', type: 'textarea', class: 'md:col-span-2' },
      { key: 'active', label: 'Activo', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'name', label: 'Cliente' },
      { key: 'nit', label: 'NIT' },
      { key: 'phone', label: 'Telefono' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
    formClass: 'md:grid-cols-2',
  },
  suppliers: {
    title: 'Proveedores',
    description: 'Proveedores usados en compras, entradas y costos.',
    endpoint: '/suppliers',
    collectionKey: 'suppliers',
    resourceKey: 'supplier',
    permission: 'suppliers.read',
    writePermission: 'suppliers.write',
    icon: Truck,
    singularLabel: 'proveedor',
    createLabel: 'Nuevo proveedor',
    emptyTitle: 'Sin proveedores',
    emptyDescription: 'Registra proveedores antes de crear compras.',
    searchPlaceholder: 'Buscar por nombre, NIT o telefono',
    searchParam: 'name',
    fields: [
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Distribuidora Central' },
      { key: 'nit', label: 'NIT', placeholder: '0614-020290-102-0' },
      { key: 'nrc', label: 'NRC', placeholder: '654321-0' },
      { key: 'email', label: 'Correo', type: 'email', placeholder: 'ventas@proveedor.com' },
      { key: 'phone', label: 'Telefono', placeholder: '2222-1111' },
      { key: 'address', label: 'Direccion', type: 'textarea', class: 'md:col-span-2' },
      { key: 'active', label: 'Activo', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'name', label: 'Proveedor' },
      { key: 'nit', label: 'NIT' },
      { key: 'phone', label: 'Telefono' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
    formClass: 'md:grid-cols-2',
  },
  paymentMethods: {
    title: 'Metodos de pago',
    description: 'Opciones que el POS acepta para pagos simples o mixtos.',
    endpoint: '/payment_methods',
    collectionKey: 'payment_methods',
    resourceKey: 'payment_method',
    permission: 'payment_methods.read',
    writePermission: 'payment_methods.write',
    icon: CreditCard,
    singularLabel: 'metodo de pago',
    createLabel: 'Nuevo metodo',
    emptyTitle: 'Sin metodos',
    emptyDescription: 'Agrega efectivo, tarjeta, transferencia u otros metodos.',
    searchPlaceholder: 'Buscar metodo',
    fields: [
      { key: 'code', label: 'Codigo', required: true, placeholder: 'EFECTIVO' },
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Efectivo' },
      { key: 'active', label: 'Activo', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'code', label: 'Codigo' },
      { key: 'name', label: 'Metodo' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
  },
  branches: {
    title: 'Sucursales',
    description: 'Puntos de operacion del negocio con codigos fiscales y contacto.',
    endpoint: '/branches',
    collectionKey: 'branches',
    resourceKey: 'branch',
    permission: 'branches.read',
    writePermission: 'branches.write',
    icon: Building2,
    singularLabel: 'sucursal',
    createLabel: 'Nueva sucursal',
    emptyTitle: 'Sin sucursales',
    emptyDescription: 'Crea sucursales para separar ventas, cajas y bodegas.',
    searchPlaceholder: 'Buscar sucursal',
    fields: [
      { key: 'code', label: 'Codigo', required: true, placeholder: 'MATRIZ' },
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Casa matriz' },
      { key: 'phone', label: 'Telefono', placeholder: '2222-2222' },
      { key: 'establishment_code', label: 'Codigo establecimiento', placeholder: '0001' },
      { key: 'point_of_sale_code', label: 'Codigo punto de venta', placeholder: '0001' },
      { key: 'status', label: 'Estado', type: 'select', options: [{ label: 'Activa', value: 'active' }, { label: 'Inactiva', value: 'inactive' }], defaultValue: 'active' },
      { key: 'address', label: 'Direccion', type: 'textarea', class: 'md:col-span-2' },
      { key: 'is_main', label: 'Sucursal principal', type: 'boolean', defaultValue: false },
    ],
    columns: [
      { key: 'code', label: 'Codigo' },
      { key: 'name', label: 'Sucursal' },
      { key: 'phone', label: 'Telefono' },
      { key: 'status', label: 'Estado', type: 'status' },
    ],
    formClass: 'md:grid-cols-2',
  },
  warehouses: {
    title: 'Bodegas',
    description: 'Ubicaciones de stock por sucursal para ventas, compras y transferencias.',
    endpoint: '/warehouses',
    collectionKey: 'warehouses',
    resourceKey: 'warehouse',
    permission: 'warehouses.read',
    writePermission: 'warehouses.write',
    icon: Warehouse,
    singularLabel: 'bodega',
    createLabel: 'Nueva bodega',
    emptyTitle: 'Sin bodegas',
    emptyDescription: 'Crea bodegas para comenzar a manejar existencias.',
    searchPlaceholder: 'Buscar bodega',
    dependencies: [
      { key: 'branches', endpoint: '/branches', collectionKey: 'branches' },
    ],
    fields: [
      { key: 'branch_id', label: 'Sucursal', type: 'select', dependencyKey: 'branches', required: true },
      { key: 'code', label: 'Codigo', required: true, placeholder: 'BOD-MATRIZ' },
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Bodega matriz' },
      { key: 'active', label: 'Activa', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'code', label: 'Codigo' },
      { key: 'name', label: 'Bodega' },
      { key: 'branch_name', label: 'Sucursal' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
  },
  registers: {
    title: 'Cajas',
    description: 'Terminales POS por sucursal para apertura y cierre de caja.',
    endpoint: '/cash_registers',
    collectionKey: 'cash_registers',
    resourceKey: 'cash_register',
    permission: 'cash_registers.read',
    writePermission: 'cash_registers.write',
    icon: Store,
    singularLabel: 'caja',
    createLabel: 'Nueva caja',
    emptyTitle: 'Sin cajas',
    emptyDescription: 'Crea cajas por sucursal para que el POS pueda abrir y cerrar sesiones.',
    searchPlaceholder: 'Buscar caja',
    dependencies: [
      { key: 'branches', endpoint: '/branches', collectionKey: 'branches' },
    ],
    fields: [
      { key: 'branch_id', label: 'Sucursal', type: 'select', dependencyKey: 'branches', required: true },
      { key: 'code', label: 'Codigo', required: true, placeholder: 'CAJA-01' },
      { key: 'name', label: 'Nombre', required: true, placeholder: 'Caja principal' },
      {
        key: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'available',
        options: [
          { label: 'Disponible', value: 'available' },
          { label: 'En uso', value: 'in_use' },
          { label: 'Inactiva', value: 'inactive' },
        ],
      },
    ],
    columns: [
      { key: 'code', label: 'Codigo' },
      { key: 'name', label: 'Caja' },
      { key: 'branch_name', label: 'Sucursal' },
      { key: 'status', label: 'Estado', type: 'status' },
      { key: 'current_cash_session_id', label: 'Sesion actual' },
    ],
  },
  users: {
    title: 'Usuarios permitidos',
    description: 'Usuarios del negocio y roles operativos disponibles para este tenant.',
    endpoint: '/users',
    collectionKey: 'users',
    resourceKey: 'user',
    permission: 'users.read',
    writePermission: 'users.write',
    icon: UserRound,
    singularLabel: 'usuario',
    createLabel: 'Nuevo usuario',
    emptyTitle: 'Sin usuarios',
    emptyDescription: 'Invita usuarios y asigna roles permitidos para operar el negocio.',
    searchPlaceholder: 'Buscar por nombre o correo',
    searchParam: 'name',
    dependencies: [
      { key: 'branches', endpoint: '/branches', collectionKey: 'branches' },
      {
        key: 'roles',
        endpoint: '/roles',
        collectionKey: 'roles',
        filter: (record) => record.name !== 'superadmin',
      },
    ],
    fields: [
      { key: 'full_name', label: 'Nombre completo', required: true, placeholder: 'Carlos Cajero' },
      { key: 'email', label: 'Correo', type: 'email', required: true, placeholder: 'usuario@example.com' },
      { key: 'branch_id', label: 'Sucursal', type: 'select', dependencyKey: 'branches' },
      { key: 'role_ids', label: 'Roles permitidos', type: 'multiselect', dependencyKey: 'roles', class: 'md:col-span-2' },
      { key: 'password', label: 'Contrasena', type: 'password', placeholder: 'Solo para crear o cambiar' },
      { key: 'password_confirmation', label: 'Confirmar contrasena', type: 'password', placeholder: 'Repite la contrasena' },
      { key: 'active', label: 'Activo', type: 'boolean', defaultValue: true },
    ],
    columns: [
      { key: 'full_name', label: 'Usuario' },
      { key: 'email', label: 'Correo' },
      { key: 'branch_name', label: 'Sucursal' },
      { key: 'roles', label: 'Roles', type: 'roles' },
      { key: 'active', label: 'Estado', type: 'boolean' },
    ],
    formClass: 'md:grid-cols-2',
  },
  catalogOverview: {
    title: 'Catalogos',
    description: 'Accesos rapidos a productos, clasificaciones y entidades comerciales.',
    endpoint: '',
    collectionKey: '',
    resourceKey: '',
    permission: 'products.read',
    writePermission: 'products.write',
    icon: Boxes,
    singularLabel: 'catalogo',
    createLabel: '',
    emptyTitle: '',
    emptyDescription: '',
    searchPlaceholder: '',
    fields: [],
    columns: [],
  },
}
